name: Create release
on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'
jobs:
  release:
    name: Create release with packages
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Install wine
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -fy wine64
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build app
        shell: bash
        run: |
          yarn
          yarn build
      - name: Create packages
        run: yarn package:all
      - name: Zip packages
        run: yarn packages:zip
      - name: Upload macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/git-switch-macos.zip
          asset_name: git-switch-macos.zip
          asset_content_type: application/zip
      - name: Upload linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/git-switch-linux.zip
          asset_name: git-switch-linux.zip
          asset_content_type: application/zip
      - name: Upload windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/git-switch-windows.zip
          asset_name: git-switch-windows.zip
          asset_content_type: application/zip
